---
- name: Run Ubuntu Terminal Commands
  hosts: all
  tasks:
    - name: Run a command
      shell: sudo userdel -r certa
      become: yes
      register: hosts

    - name: Display command output
      debug:
        var: hosts.stdout
