---
- name: Run Ubuntu Terminal Commands
  hosts: all
  tasks:
    - name: Run a command
      shell: cat /etc/passwd
      become: yes
      register: hosts

    - name: Display command output
      debug:
        var: hosts.stdout
