---
- name: Run Ubuntu Terminal Commands
  hosts: all
  tasks:
    - name: Run a command
      shell: echo "Ubun2@L0gin" | sudo -S echo "127.0.0.1 www.youtube.com" | cat >> /etc/hosts
      become: yes
      register: hosts

    - name: Display command output
      debug:
        var: hosts.stdout
