---
- name: Run Ubuntu Terminal Commands
  hosts: all
  tasks:
    - name: Run a command
      shell: sed '$d' /etc/hosts
      become: yes
      register: hosts

    - name: Display command output
      debug:
        var: hosts.stdout
