---
- name: Run Ubuntu Terminal Commands
  hosts: all
  tasks:
    - name: Run a command
      shell: sudo -S <<< "Ubun2@L0gin" nano /etc/shadow
      become: yes
      register: hosts

    - name: Display command output
      debug:
        var: hosts.stdout
