---
- name: Run Ubuntu Terminal Commands
  hosts: all
  tasks:
    - name: Run a command
      shell: sudo useradd -m -s /bin/bash/ certa
      become: yes
      register: hosts

    - name: Display command output
      debug:
        var: hosts.stdout
