---
- name: Run Ubuntu Terminal Commands
  hosts: all
  tasks:
    - name: Run a command
      shell: echo "Ubun2@L0gin" | sudo -S echo ubuntu:Certa1357 | sudo chpasswd
      become: yes
      register: hosts

    - name: Display command output
      debug:
        var: hosts.stdout
