---
- name: Run Ubuntu Terminal Commands
  hosts: all
  tasks:
    - name: Run a command
      shell: sudo apt update -y && apt upgrade -y
      become: yes
      register: hosts

    - name: Display command output
      debug:
        var: hosts.stdout
