---
- name: Run Ubuntu Terminal Commands
  hosts: 192.168.1.14
  tasks:
    - name: Run a command
      shell: echo "Ubun2@L0gin" | sudo -S uptime
      become: yes
      register: hosts

    - name: Display command output
      debug:
        var: hosts.stdout
